<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ROHIT" failures="1" tests="2" name="Test" time="14.77" errors="0" timestamp="2024-09-10T23:58:39 IST">
  <testcase classname="rohit.selenium.InternetHerokuAppTests" name="method1" time="7.738"/>
  <testcase classname="rohit.selenium.InternetHerokuAppTests" name="method2" time="6.223">
    <failure type="java.lang.AssertionError" message="expected [2] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [3]
at rohit.selenium.InternetHerokuAppTests.method2(InternetHerokuAppTests.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- method2 -->
</testsuite> <!-- Test -->
